[project]
authors = ["Emily Herbert"]
entry = "main.sw"
license = "Apache-2.0"
name = "counter_contract"

[dependencies]
std = { git = "https://github.com/FuelLabs/sway", branch = "master" }
counter_abi = { path = "../counter_abi" }
